package common

var RKEY_V_ID_PTR = "V_ID_PTR"
var RKEY_H_NAME = "H_NAME_ID"
var RKEY_H_INFO = "H_ID_INFO"
var RKEY_H_EQW = "H_ID_EQW"
var RKEY_H_EQA = "H_ID_EQA"
var RKEY_H_EQR = "H_ID_EQR"

var RKEY_H_CODE = "H_CODE"

var RKEY_Z_TOP_FHT = "Z_TOPLIST_FHT"
var RKEY_Z_TOP_KNT = "Z_TOPLIST_KNT"
var RKEY_Z_TOP_ROG = "Z_TOPLIST_ROG"
var RKEY_Z_TOP_NEC = "Z_TOPLIST_NEC"
